247 org page template
CivicTechTO/women-and-color-frontend pull request #255
Opened 2018-10-14 18:59 UTC by rosexw

This is for issue: "Create page template for organization page #247"
http://localhost:8080/#/organization/123/org-name
A new page is created for this and it only shows a header for us to add the details when we receive them later.

2018-10-14 22:35 UTC, s-kennedy requested changes

2018-10-14 22:35 UTC, s-kennedy commented on app/config/routes.js
> +          <Route path="/blah" component={Speaker} />
do we really need this lol

2018-10-14 22:35 UTC, s-kennedy commented on app/pages/Onboarding/Profile/Profile.js
> +        <FormField fullWidth className={css.formControl}>
This is from a different PR, right?

2018-10-14 22:35 UTC, s-kennedy commented on app/pages/Home/components/Filters.js
> +                selected = !searchParams['poc'] && !searchParams['woman'] && !searchParams['lgbtqa'];
This is from a different PR right?

2018-10-14 23:58 UTC, rosexw commented
@s-kennedy, fixed!

2018-11-03 23:24 UTC, merged

2018-11-03 23:24 UTC, s-kennedy commented
@rosexw Thank you!!