Addition/add load spinners to front page
CivicTechTO/women-and-color-frontend pull request #256
Opened 2018-10-14 20:04 UTC by rosexw

When the front page loads the list of Speakers, it shows "no results" before showing the results. This could be a bad user experience. So I copied the loading spinner from the Speaker page to the home page for loading the speakers and loading more speakers (when user presses on "Load More Speakers"). There are currently two spinners: isLoading and isLoadingMore because isLoading is for an empty results list and isLoadingMore shows the spinner where the "Load More Speakers" button was.

One question is, do you want the load more spinner to replace the load more button, as it is now, or do you want the spinner below the button?

FOR TESTING:
You may need to set it to Slow 3G mode to see the spinner working and it takes a few seconds before it shows. Also, in the constants.js file from App>helpers, you'll need to set the speakers limit to 1 or 2, so the load more button shows up.

2018-10-14 22:42 UTC, s-kennedy requested changes
Can you remove the Backend submodule please?

2018-10-14 22:56 UTC, s-kennedy requested changes

2018-10-14 22:56 UTC, s-kennedy commented on app/pages/Home/components/SpeakerList.js
> +const SpeakerList = ({ speakers, endOfResults, loadMoreSpeakers, isLoading, isLoadingMore }) => {
I don't think we need `isLoadingMore`. The spinner and the "No results" can both replace where the Speakers would go, on line 23. We just need to change the logic there. So if it's `isLoading`, put the spinner. For `!isLoading && noResults`, put "No results". For `!isLoading && !noResults`, render out the speakers.

2018-10-14 22:56 UTC, s-kennedy commented on app/pages/Home/components/SpeakerList.js
> +          {isLoadingMore ? <ReactLoading type="spinningBubbles" color="#E5E8F4" /> :
and here, instead of showing either the spinner or the button, only show the button if `!isLoading && !endOfResults`

2018-10-14 22:56 UTC, s-kennedy commented on app/pages/Home/components/SpeakerList.js
> +          {isLoadingMore ? <ReactLoading type="spinningBubbles" color="#E5E8F4" /> :
and here, instead of showing either the spinner or the button, only show the button if `!isLoading && !endOfResults`

2018-10-20 22:06 UTC, rosexw commented
Hi @s-kennedy  - please see my changes. I have removed the isLoadingMore feature and turned the spinners into buttons with the text "Loading..." as per you and Mohammed suggested. The backend is removed from this push. Thank you!

2018-11-03 23:23 UTC, s-kennedy approved these changes

2018-11-03 23:23 UTC, merged